[[greetings]]
japanese = "おはよう"
english = "Good morning"
    
[[greetings]]
japanese = "おはようございます"
english = "Good morning (polite)"
    
[[greetings]]
japanese = "おやすみ（なさい）"
english = "Good night"
    
[[greetings]]
japanese = "ごちそうさま（でした）"
english = "Thank you for the meal (after eating)"
    
[[greetings]]
japanese = "よろしくおねがいします"
english = "Nice to meet you"
    
[[greetings]]
japanese = "はじめまして"
english = "How do you do?"
    
[[greetings]]
japanese = "すみません"
english = "Excuse me;I'm sorry"
    
[[greetings]]
japanese = "ただいま"
english = "I'm home"
    
[[greetings]]
japanese = "さようなら"
english = "Good bye"
    
[[greetings]]
japanese = "こんばんは"
english = "Good evening"
    
[[greetings]]
japanese = "こんにちは"
english = "Good afternoon"
    
[[greetings]]
japanese = "おかえり（なさい）"
english = "Welcome home"
    
[[greetings]]
japanese = "いってらっしゃい"
english = "Please go and come back"
    
[[greetings]]
japanese = "いってきます"
english = "I’ll go and come back"
    
[[greetings]]
japanese = "いいえ"
english = "No;Not at all"
    
[[greetings]]
japanese = "ありがとうございます"
english = "Thank you (polite)"
    
[[greetings]]
japanese = "ありがとう"
english = "Thank you"